### ISSUE TITLE
能支持鸿蒙系统识别吗？

### ISSUE THREAD

**Issue by chenleno** [skillnull/DeviceJs#20]
**Is your feature request related to a problem? Please describe.**
目前版本的测试页面跑在鸿蒙系统手机上，OS和OSVersion 不能有效识别
**Describe the solution you'd like**
鸿蒙系统的OS和OSVersion能正确识别

**Describe alternatives you've considered**

**Additional context**

**Comment by skillnull** [comment]
> **Is your feature request related to a problem? Please describe.** 目前版本的测试页面跑在鸿蒙系统手机上，OS和OSVersion 不能有效识别 **Describe the solution you'd like** 鸿蒙系统的OS和OSVersion能正确识别
> 
> **Describe alternatives you've considered**
> 
> **Additional context**

请给出具体不能识别的系统版本和手机型号，以及浏览器版信息
